🚧 Update to SDK 33.0.0
🏭 This commit was automatically generated by generate-modules-sdk script.

Fix of this commit will be marked as:
🏃🏿‍♀️🚴‍♂️🧕🏽😨

Full error log:
Error:  asset 2023-1-2--22-50-46--a174a34b-0778-4e0f-9e05-962a08ceccb9/main.min.js 839 KiB [emitted] (name: main) 1 related asset
runtime modules 670 bytes 3 modules
modules by path ./node_modules/rxjs/_esm5/internal/ 314 KiB 198 modules
modules by path ./node_modules/uuid/dist/esm-browser/*.js 19.1 KiB 15 modules
modules by path ./node_modules/destroyable/dist/ 38 KiB
  modules by path ./node_modules/destroyable/dist/*.js 35.4 KiB 10 modules
  modules by path ./node_modules/destroyable/dist/errors/*.js 2.59 KiB
    ./node_modules/destroyable/dist/errors/CollisionError.js 1.3 KiB [built] [code generated]
    ./node_modules/destroyable/dist/errors/NotFoundError.js 1.29 KiB [built] [code generated]
modules by path ./node_modules/waitasecond/dist/ 18 KiB 12 modules
modules by path ./src/ 61.2 KiB
  modules by path ./src/message-api/ 46.6 KiB 5 modules
  modules by path ./src/systems/*.tsx 14.3 KiB 3 modules
  ./src/index.ts 356 bytes [built] [code generated]
6 modules

ERROR in C:\Users\me\work\collboard\collboard-admin\src\message-api\hedu.tsx
./src/message-api/hedu.tsx 27:14-27
[tsl] ERROR in C:\Users\me\work\collboard\collboard-admin\src\message-api\hedu.tsx(27,15)
      TS2345: Argument of type '{ manifest: { name: string; version: string; description: string; contributors: string[]; license: string; repository: { type: string; url: string; }; title: string; flags: { isHidden: true; }; }; place: UserInterfaceElementPlace.EdgeTop; createElement(systems: any): Promise<...>; }' is not assignable to parameter of type '{ manifest?: IModuleManifest | undefined; place: UserInterfaceElementPlace; order?: number | undefined; render(systems: ISystems): Promisable<...>; }'.
  Object literal may only specify known properties, and 'createElement' does not exist in type '{ manifest?: IModuleManifest | undefined; place: UserInterfaceElementPlace; order?: number | undefined; render(systems: ISystems): Promisable<...>; }'.
 @ ./src/index.ts 3:0-29

ERROR in C:\Users\me\work\collboard\collboard-admin\src\message-api\hedu.tsx
./src/message-api/hedu.tsx 27:28-35
[tsl] ERROR in C:\Users\me\work\collboard\collboard-admin\src\message-api\hedu.tsx(27,29)
      TS7006: Parameter 'systems' implicitly has an 'any' type.
 @ ./src/index.ts 3:0-29

webpack 5.35.1 compiled with 2 errors in 7732 ms
Error:
    at DevelopmentCompiler.<anonymous> (C:\Users\me\work\collboard\collboard-admin\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:91:37)
    at Generator.next (<anonymous>)
    at C:\Users\me\work\collboard\collboard-admin\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\me\work\collboard\collboard-admin\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:4:12)
    at Watching.handler (C:\Users\me\work\collboard\collboard-admin\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:85:72)
    at C:\Users\me\work\collboard\collboard-admin\node_modules\webpack\lib\Watching.js:204:9
    at Hook.eval [as callAsync] (eval at create (C:\Users\me\work\collboard\collboard-admin\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\me\work\collboard\collboard-admin\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
    at Watching._done (C:\Users\me\work\collboard\collboard-admin\node_modules\webpack\lib\Watching.js:201:28)